<div class="space-y-6 print:space-y-4">
    <!-- Header & Filter (Hidden in Print) -->
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 print:hidden">
        <div>
            <h2 class="text-2xl font-bold text-gray-800 dark:text-white">Laporan Bulanan</h2>
            <p class="text-gray-500 dark:text-gray-400 mt-1">Ringkasan aktivitas CSIRT</p>
        </div>
        
        <form action="" method="GET" class="flex gap-2 bg-white dark:bg-slate-800 p-2 rounded-lg shadow-sm border border-gray-200 dark:border-slate-700">
            <select name="month" class="px-3 py-1 bg-transparent border-none focus:ring-0 text-sm dark:text-gray-300">
                <?php for($m=1; $m<=12; $m++): $mm = str_pad($m, 2, '0', STR_PAD_LEFT); ?>
                    <option value="<?= $mm ?>" <?= $selected_month == $mm ? 'selected' : '' ?>>
                        <?= date('F', mktime(0, 0, 0, $m, 10)) ?>
                    </option>
                <?php endfor; ?>
            </select>
            <select name="year" class="px-3 py-1 bg-transparent border-none focus:ring-0 text-sm dark:text-gray-300">
                <?php for($y=date('Y'); $y>=2024; $y--): ?>
                    <option value="<?= $y ?>" <?= $selected_year == $y ? 'selected' : '' ?>><?= $y ?></option>
                <?php endfor; ?>
            </select>
            <button type="submit" class="px-3 py-1 bg-blue-600 text-white rounded text-sm hover:bg-blue-700">Filter</button>
            <button type="button" onclick="window.print()" class="px-3 py-1 bg-gray-600 text-white rounded text-sm hover:bg-gray-700 flex items-center gap-1">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
                Print
            </button>
        </form>
    </div>

    <!-- Report Title (Print Only) -->
    <div class="hidden print:block text-center mb-8 border-b pb-4">
        <h1 class="text-3xl font-bold text-gray-900">CSIRT RRI - Executive Report</h1>
        <p class="text-gray-600 mt-2">Periode: <?= date('F', mktime(0, 0, 0, $selected_month, 10)) ?> <?= $selected_year ?></p>
        <p class="text-sm text-gray-500 mt-1">Generated by System: <?= date('d M Y H:i') ?></p>
    </div>

    <!-- Stats Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 print:grid-cols-4 print:gap-4">
        <!-- Stat Card 1 -->
        <div class="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-gray-200 dark:border-slate-700 print:border print:shadow-none">
            <div class="flex justify-between items-start">
                <div>
                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Bukti Digital Baru</p>
                    <h3 class="text-3xl font-bold text-gray-800 dark:text-white mt-2" data-count-up="<?= $total_evidence ?>"><?= $total_evidence ?></h3>
                </div>
                <div class="p-2 bg-indigo-50 dark:bg-indigo-900/30 rounded-lg text-indigo-600 dark:text-indigo-400">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                </div>
            </div>
            <p class="text-xs text-gray-400 mt-4">File Evidence Uploaded</p>
        </div>

        <!-- Stat Card 2 -->
        <div class="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-gray-200 dark:border-slate-700 print:border print:shadow-none">
            <div class="flex justify-between items-start">
                <div>
                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Panduan Baru</p>
                    <h3 class="text-3xl font-bold text-gray-800 dark:text-white mt-2" data-count-up="<?= $total_kb ?>"><?= $total_kb ?></h3>
                </div>
                <div class="p-2 bg-blue-50 dark:bg-blue-900/30 rounded-lg text-blue-600 dark:text-blue-400">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"/></svg>
                </div>
            </div>
            <p class="text-xs text-gray-400 mt-4">Knowledge Base Articles</p>
        </div>

        <!-- Stat Card 3 -->
        <div class="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-gray-200 dark:border-slate-700 print:border print:shadow-none">
            <div class="flex justify-between items-start">
                <div>
                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Login Sukses</p>
                    <h3 class="text-3xl font-bold text-green-600 dark:text-green-400 mt-2" data-count-up="<?= $login_success ?>"><?= $login_success ?></h3>
                </div>
                <div class="p-2 bg-green-50 dark:bg-green-900/30 rounded-lg text-green-600 dark:text-green-400">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"/></svg>
                </div>
            </div>
            <div class="mt-4 flex items-center gap-2">
                 <span class="text-xs font-medium text-red-500"><?= $login_failed ?> Gagal</span>
                 <div class="h-1 flex-1 bg-gray-100 dark:bg-slate-700 rounded-full overflow-hidden">
                     <?php 
                        $total_login = $login_success + $login_failed; 
                        $percent = $total_login > 0 ? ($login_failed / $total_login) * 100 : 0;
                     ?>
                     <div class="h-full bg-red-500" style="width: <?= $percent ?>%"></div>
                 </div>
            </div>
        </div>
        
         <!-- Stat Card 4 -->
        <div class="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-gray-200 dark:border-slate-700 print:border print:shadow-none">
            <div class="flex justify-between items-start">
                <div>
                    <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Berita Publik</p>
                    <h3 class="text-3xl font-bold text-gray-800 dark:text-white mt-2" data-count-up="<?= $total_articles ?>"><?= $total_articles ?></h3>
                </div>
                 <div class="p-2 bg-orange-50 dark:bg-orange-900/30 rounded-lg text-orange-600 dark:text-orange-400">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z"/></svg>
                </div>
            </div>
             <p class="text-xs text-gray-400 mt-4">Published News</p>
        </div>
    </div>

    <!-- Recent Logs Table -->
    <div class="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-gray-200 dark:border-slate-700 overflow-hidden print:border print:shadow-none mt-8">
        <div class="px-6 py-4 border-b border-gray-200 dark:border-slate-700 bg-gray-50 dark:bg-slate-700/50">
            <h3 class="font-semibold text-gray-800 dark:text-white">Aktivitas Sistem Terbaru (Sample)</h3>
        </div>
        <table class="w-full text-left text-sm">
            <thead class="bg-gray-50 dark:bg-slate-700/50 text-gray-600 dark:text-gray-300 border-b border-gray-200 dark:border-slate-700">
                <tr>
                    <th class="px-6 py-3">Waktu</th>
                    <th class="px-6 py-3">User</th>
                    <th class="px-6 py-3">Module - Action</th>
                    <th class="px-6 py-3">IP Address</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 dark:divide-slate-700">
                <?php if (empty($recent_logs)): ?>
                <tr><td colspan="4" class="px-6 py-4 text-center text-gray-500">Tidak ada log aktivitas.</td></tr>
                <?php else: ?>
                    <?php foreach($recent_logs as $log): ?>
                    <tr>
                        <td class="px-6 py-3 whitespace-nowrap text-gray-500 dark:text-gray-400">
                            <?= date('d M Y H:i:s', strtotime($log['created_at'])) ?>
                        </td>
                        <td class="px-6 py-3 font-medium text-gray-900 dark:text-white">
                            <?= $log['username'] ?? 'System/Guest' ?>
                        </td>
                        <td class="px-6 py-3">
                            <span class="px-2 py-1 rounded text-xs font-semibold bg-gray-100 dark:bg-slate-700">
                                <?= $log['module'] ?>
                            </span>
                            <span class="ml-2 text-gray-600 dark:text-gray-300"><?= $log['action'] ?></span>
                        </td>
                        <td class="px-6 py-3 text-gray-500 font-mono text-xs">
                            <?= $log['ip_address'] ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>

    <!-- Footer for Print -->
    <div class="hidden print:block mt-20 text-center text-gray-500 text-sm">
        <p>This document is confidential and intended for authorized personnel only.</p>
        <p>CSIRT RRI - <?= date('Y') ?></p>
    </div>
</div>
