<!-- Network Traffic MRTG - Multi Host Grid -->
<style>
    .mrtg-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 16px;
    }
    @media (max-width: 992px) {
        .mrtg-grid { grid-template-columns: 1fr; }
    }
    .mrtg-card {
        background: #fff;
        border: 1px solid #e0e0e0;
        border-radius: 4px;
        overflow: hidden;
    }
    .mrtg-card-title {
        font-size: 13px;
        font-weight: 700;
        color: #333;
        padding: 8px 12px 2px 12px;
        margin: 0;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }
    .mrtg-chart-container {
        width: 100%;
        height: 220px;
    }
    .mrtg-legend {
        padding: 4px 10px 8px 10px;
        font-size: 11px;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    .mrtg-legend-row {
        display: flex;
        align-items: center;
        gap: 6px;
        margin-bottom: 2px;
        flex-wrap: wrap;
    }
    .mrtg-legend-color {
        width: 14px;
        height: 4px;
        flex-shrink: 0;
    }
    .mrtg-legend-label {
        flex: 1;
        color: #555;
        min-width: 0;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
    .mrtg-legend-stats {
        display: flex;
        gap: 8px;
        color: #333;
        font-size: 10.5px;
        flex-shrink: 0;
    }
    .mrtg-legend-stats span {
        white-space: nowrap;
    }
    .mrtg-legend-stats .stat-label {
        color: #999;
        font-size: 10px;
    }
    .mrtg-header-bar {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 12px 16px;
        margin-bottom: 16px;
        background: #fff;
        border-radius: 6px;
        border: 1px solid #e0e0e0;
    }
    .mrtg-header-bar h4 {
        margin: 0;
        font-size: 16px;
        font-weight: 700;
        color: #333;
    }
    .mrtg-header-bar .mrtg-live {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        background: rgba(45,142,45,0.08);
        color: #2d8e2d;
        font-size: 11px;
        font-weight: 600;
        padding: 4px 12px;
        border-radius: 20px;
        letter-spacing: 0.5px;
    }
    .mrtg-live .dot {
        width: 7px;
        height: 7px;
        border-radius: 50%;
        background: #2d8e2d;
        animation: pulse-dot 1.5s infinite;
    }
    @keyframes pulse-dot {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.3; }
    }
    .mrtg-footer {
        text-align: center;
        padding: 10px;
        font-size: 11px;
        color: #999;
    }
</style>

<div class="mrtg-header-bar">
    <h4><i class="fas fa-network-wired mr-2 text-primary"></i>Network Traffic MRTG</h4>
    <div>
        <span class="mrtg-live"><span class="dot"></span> LIVE MONITORING</span>
        <span class="ml-3 text-muted" style="font-size:11px;">Updated: <span id="mrtg-last-update">-</span></span>
    </div>
</div>

<div class="mrtg-grid" id="mrtg-grid">
    <!-- Cards generated by JS -->
</div>

<div class="mrtg-footer">
    Auto-refreshes every 60 seconds
</div>

<!-- ECharts -->
<script src="https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"></script>

<script>
document.addEventListener('DOMContentLoaded', function() {

    // =====================================================
    // Host config matching the PHP model order exactly
    // =====================================================
    const HOSTS = [
        { label: 'ASTINET',                              inId: '66918',  outId: '66942'  },
        { label: 'FIBERNET GEDUNG MBC PUSBANGKOM 300Mbps', inId: '373160', outId: '373193' },
        { label: 'FIBERNET',                             inId: '407210', outId: '407255' },
        { label: 'FIBERNET BINA PROFESI',                inId: '374148', outId: '374166' },
        { label: 'ASTINET TUNNEL',                       inId: '374437', outId: '374458' },
        { label: 'FIBERNET PUSBANGKOM',                  inId: '406908', outId: '406956' },
        { label: 'FIBERNET DC DPOK',                     inId: '413803', outId: '413821' },
        { label: 'FIBERNET SPI',                         inId: '423530', outId: '423587' },
        { label: 'INTERNET DC JKT (Fibernet)',           inId: '41470',  outId: '41536'  },
        { label: 'FIBERNET PEMANCAR KEBAYORAN',          inId: '407499', outId: '407604' },
        { label: 'INTERNET RRI KANTOR PUSAT (Fibernet)', inId: '370159', outId: '370237' },
        { label: 'FIBERNET DC PDN',                      inId: '369924', outId: '370002' }
    ];

    const charts = [];   // ECharts instances
    const grid = document.getElementById('mrtg-grid');

    // =====================================================
    // Build card DOM for each host
    // =====================================================
    HOSTS.forEach((host, idx) => {
        const card = document.createElement('div');
        card.className = 'mrtg-card';
        card.id = 'mrtg-card-' + idx;
        card.innerHTML = `
            <div class="mrtg-card-title">${host.label}</div>
            <div class="mrtg-chart-container" id="chart-${idx}"></div>
            <div class="mrtg-legend" id="legend-${idx}">
                <div class="mrtg-legend-row">
                    <div class="mrtg-legend-color" style="background:#e64a19;"></div>
                    <span class="mrtg-legend-label" id="out-label-${idx}">Loading...</span>
                    <div class="mrtg-legend-stats">
                        <span><span class="stat-label">[avg]</span> <span id="out-avg-${idx}">-</span></span>
                        <span><span class="stat-label">min</span> <span id="out-min-${idx}">-</span></span>
                        <span><span class="stat-label">avg</span> <span id="out-tavg-${idx}">-</span></span>
                        <span><span class="stat-label">max</span> <span id="out-max-${idx}">-</span></span>
                    </div>
                </div>
                <div class="mrtg-legend-row">
                    <div class="mrtg-legend-color" style="background:#2d8e2d;"></div>
                    <span class="mrtg-legend-label" id="in-label-${idx}">Loading...</span>
                    <div class="mrtg-legend-stats">
                        <span><span class="stat-label">[avg]</span> <span id="in-avg-${idx}">-</span></span>
                        <span><span class="stat-label">min</span> <span id="in-min-${idx}">-</span></span>
                        <span><span class="stat-label">avg</span> <span id="in-tavg-${idx}">-</span></span>
                        <span><span class="stat-label">max</span> <span id="in-max-${idx}">-</span></span>
                    </div>
                </div>
            </div>
        `;
        grid.appendChild(card);

        // Initialize ECharts instance
        const chartDom = document.getElementById('chart-' + idx);
        const chart = echarts.init(chartDom);
        charts.push(chart);
        chart.setOption(getChartOption());
    });

    // =====================================================
    // Chart option template (MRTG style)
    // =====================================================
    function getChartOption() {
        return {
            grid: {
                top: 10, left: 50, right: 20, bottom: 40
            },
            tooltip: {
                trigger: 'axis',
                axisPointer: { type: 'cross', label: { backgroundColor: '#6a7985' } },
                formatter: function(params) {
                    let res = '<div style="font-weight:bold;margin-bottom:4px;">' + params[0].axisValueLabel + '</div>';
                    params.forEach(item => {
                        res += '<div style="display:flex;justify-content:space-between;gap:16px;">'
                            + '<span>' + item.marker + ' ' + item.seriesName + ':</span>'
                            + '<span style="font-weight:bold;">' + formatBits(item.value) + '</span>'
                            + '</div>';
                    });
                    return res;
                }
            },
            legend: { show: false },
            xAxis: {
                type: 'category',
                boundaryGap: false,
                data: [],
                axisLine: { lineStyle: { color: '#ccc' } },
                axisLabel: {
                    color: '#999', fontSize: 9,
                    rotate: 45,
                    formatter: function(v) {
                        // Show shorter time
                        return v;
                    }
                },
                axisTick: { show: false }
            },
            yAxis: {
                type: 'value',
                axisLabel: {
                    formatter: function(v) { return formatBits(v, 0); },
                    color: '#999', fontSize: 9
                },
                splitLine: { lineStyle: { type: 'dashed', color: '#eee' } },
                axisLine: { show: false },
                axisTick: { show: false }
            },
            series: [
                {
                    name: 'Bits sent',
                    type: 'line',
                    data: [],
                    smooth: false,
                    symbol: 'none',
                    lineStyle: { color: '#e64a19', width: 1 },
                    itemStyle: { color: '#e64a19' },
                    areaStyle: {
                        color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
                            { offset: 0, color: 'rgba(230,74,25,0.7)' },
                            { offset: 1, color: 'rgba(230,74,25,0.05)' }
                        ])
                    },
                    z: 2
                },
                {
                    name: 'Bits received',
                    type: 'line',
                    data: [],
                    smooth: false,
                    symbol: 'none',
                    lineStyle: { color: '#2d8e2d', width: 1 },
                    itemStyle: { color: '#2d8e2d' },
                    areaStyle: {
                        color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
                            { offset: 0, color: 'rgba(45,142,45,0.7)' },
                            { offset: 1, color: 'rgba(45,142,45,0.05)' }
                        ])
                    },
                    z: 1
                }
            ]
        };
    }

    // =====================================================
    // Format bits to human readable
    // =====================================================
    function formatBits(value, decimals) {
        if (decimals === undefined) decimals = 2;
        if (!value || value === 0) return '0 bps';
        const abs = Math.abs(value);
        const units = ['bps', 'Kbps', 'Mbps', 'Gbps', 'Tbps'];
        const k = 1000;
        const i = Math.floor(Math.log(abs) / Math.log(k));
        const idx = Math.min(i, units.length - 1);
        return (value / Math.pow(k, idx)).toFixed(decimals) + ' ' + units[idx];
    }

    // =====================================================
    // Fetch data from backend
    // =====================================================
    async function fetchData() {
        try {
            const basePath = window.location.pathname.split('/admin/')[0];
            const fetchUrl = basePath + '/admin/traffic/mrtg';

            const response = await fetch(fetchUrl);
            const data = await response.json();
            console.log('MRTG Data:', data);

            if (data.success && data.hosts) {
                data.hosts.forEach((host, idx) => {
                    if (idx >= HOSTS.length) return;

                    // Prepare time labels & data arrays
                    const inData  = host.in_data || [];
                    const outData = host.out_data || [];

                    // Build aligned timestamps from IN data (or OUT if IN is empty)
                    const sourceData = inData.length >= outData.length ? inData : outData;
                    const timestamps = sourceData.map(d => {
                        const date = new Date(d.clock * 1000);
                        const h = date.getHours().toString().padStart(2, '0');
                        const m = date.getMinutes().toString().padStart(2, '0');
                        // Include AM/PM style
                        const ampm = date.getHours() >= 12 ? 'PM' : 'AM';
                        let hour12 = date.getHours() % 12;
                        if (hour12 === 0) hour12 = 12;
                        return hour12 + ':' + m + ' ' + ampm;
                    });

                    const inValues  = inData.map(d => d.value_avg);
                    const outValues = outData.map(d => d.value_avg);

                    // Update chart
                    charts[idx].setOption({
                        xAxis: { data: timestamps },
                        series: [
                            { data: outValues },  // Sent (red/orange) - OUT
                            { data: inValues }     // Received (green) - IN
                        ]
                    });

                    // Update legend labels (interface names from API)
                    const outLabel = document.getElementById('out-label-' + idx);
                    const inLabel  = document.getElementById('in-label-' + idx);
                    if (outLabel) outLabel.textContent = host.out_name || 'Bits sent';
                    if (inLabel)  inLabel.textContent  = host.in_name  || 'Bits received';

                    // Update stats (OUT = sent, IN = received)
                    updateLegendStats('out', idx, host.out_stats);
                    updateLegendStats('in',  idx, host.in_stats);
                });

                document.getElementById('mrtg-last-update').textContent = new Date().toLocaleTimeString('id-ID');
            }
        } catch (error) {
            console.error('Error fetching MRTG data:', error);
        }
    }

    function updateLegendStats(prefix, idx, stats) {
        if (!stats) return;
        const el = (id) => document.getElementById(id);
        const avg  = el(prefix + '-avg-'  + idx);
        const min  = el(prefix + '-min-'  + idx);
        const tavg = el(prefix + '-tavg-' + idx);
        const max  = el(prefix + '-max-'  + idx);

        if (avg)  avg.textContent  = formatBits(stats.last);
        if (min)  min.textContent  = formatBits(stats.min);
        if (tavg) tavg.textContent = formatBits(stats.avg);
        if (max)  max.textContent  = formatBits(stats.max);
    }

    // =====================================================
    // Init & Auto Refresh
    // =====================================================
    fetchData();
    setInterval(fetchData, 60000);

    // Handle window resize
    window.addEventListener('resize', () => {
        charts.forEach(c => c.resize());
    });
});
</script>
